### ISSUE TITLE
Uncaught ReferenceError: dt is not defined

### ISSUE THREAD

**Issue by Neb19** [ypnos-web/cakephp-datatables#11]
Hello Ypnos.

I tried to implement your fork on my cakephp application but i have a problem with Javascript.

In fault `Uncaught ReferenceError: dt is not defined` in my browser console. 
I checked several time before to post an issue. 
JS files are load correctly and in a good order.
I'm unabled to correct this problem.

do you know what it is?

Thanks you !

**Comment by ypnos-web** [comment]
`dt` is defined here: https://github.com/ypnos-web/cakephp-datatables/blob/master/webroot/js/cakephp.dataTables.js#L3

Make sure `cakephp.dataTables.js` is included correctly (early enough).

**Comment by Neb19** [comment]
Thanks you for your response. 
I confirm you that all files is well imported.
 I've checked where was defined 'dt' before to post an issue. In addition the scripts are imported in a correct order.

**Comment by ypnos-web** [comment]
Right now I really have no idea how this could fail. I suggest you provide a minimum self-contained example so that I can try this.

As a minimum I suggest you upload the page source ("View page source" in your browser) and the whole error message (with line where it occurs) to some pastebin.

Thanks.
