### ISSUE TITLE
Columns search

### ISSUE THREAD

**Issue by DmitryPostolenko** [ypnos-web/cakephp-datatables#20]
Hi,

I've installed your plugin to cakephp successfully and it works great!

The thing I can't understand is how to make column search working...

Currently, I'm adding footer after 

```
/* create new instance */
var table = $(id).dataTable(data);
```

like 

```
$("#my-table").append('<tfoot></tfoot>');
    $("#my-table thead tr").clone().appendTo($("#my-table tfoot")) ;
    $('#my-table tfoot th').each( function () {
        $(this).html( '<input type="text" placeholder="Search" />' );
    } );
```

Search is not happening.

And if I paste 

```
table.api().columns().every(function () {
        var index = this.index();
        var lastValue = ''; // closure variable to prevent redundant AJAX calls
        var timer = null; // Timer instance for delayed fetch
        $('input, select', this.footer()).on('keyup change', function () {
            if (this.value != lastValue) {
                lastValue = this.value;
                // -- set search
                table.api().column(index).search(this.value);
                window.clearTimeout(timer);
                timer = window.setTimeout(table.api().draw(), delay);
            }
        });
    });
```

just after the code, appending the footer, search somehow works, but it seems like only for the first column.

Can't really understand, what the problem is.

Thanks in advance.

**Comment by ypnos-web** [comment]
So I assume you figured that you need to do sth like this for the shipped method to be called:
```php
    'options' => [
        'init' => [
            $this->Table->callback('dt.init.columnSearch', [3]),
```

Then, it might very well be that a call to `table.api().columns().every()` registers to events on _existing_ footer elements. I suggest you create the footer in PHP and not in Javascript. If you want to hide it initially, I suggest you use CSS for that.

To use your own table HTML that includes the footer in PHP, call `$code = $this->DataTables->init($dtOptions)->draw("#{$id}");` for the javascript payload instead of `DataTables->table()`.

Now for the functionality of the `dt.init.columnSearch` function. I am sorry I do not regularly test this functionality as I don't use it myself. However I think I already spotted a bug in the use of `var lastValue` as a closure variable. Because it does not differentiate per-column. That might be a problem. In general I don't see why it should only work on the first column.

Apart from that I suggest you try the official example first and maybe we find the problem going on from there:
https://datatables.net/examples/api/multi_filter.html

It would be great if we get the problem resolved and improve the column search method included in this plugin. We could also add code so that the plugin does the footer creation (it could be done, e.g. in `dt.init.columnSearch` or as a hybrid PHP (tfoot) and JS (input) approach).

**Comment by PostD** [comment]
Hi again,

Thanks for answering so fast!
I've understood my mistake with the footer, tried to create template table with PHP.
Unfortunately, it seems like I didn't understand this part of your answer:
> To use your own table HTML that includes the footer in PHP, call $code = $this->DataTables->init($dtOptions)->draw("#{$id}"); for the javascript payload instead of DataTables->table().
I've tried to make so in few different ways, also explored fheider's plugin to have a better understanding, but no success.
Could you please explain?

Regards

**Comment by PostD** [comment]
Made it working in my way...

Code under 
```
    /* create new instance */
    var table = $(id).dataTable(data);
```
```
$('#datatable thead th').each( function () {
        var title = $('#datatable tfoot th').eq( $(this).index() ).text();
        $(this).html( '<input type="text" placeholder="Search" />' );
    } );


    table.api().columns().every(function () {
        var delay = 1000;
        var index = this.index();
        var lastValue = ''; // closure variable to prevent redundant AJAX calls
        var timer = null; // Timer instance for delayed fetch
        $('input, select', this.header()).on('keyup change', function () {
            if (this.value != lastValue) {
                lastValue = this.value;
                // -- set search
                table.api().column(index).search(this.value);
                window.clearTimeout(timer);
                timer = window.setTimeout(function() {
                    table.api().draw()
                }, delay);
            }
        });
    });
```
Also a bit modified timer not to get Unexpected identifier...

And commented call requested initializer methods code, now it seems to work just fine...

Thanks for your help.

**Comment by dividedbynothing** [comment]
Hello DmitryPostolenko, can you provide anymore information on how you got the mutli-filter working?
I've got a working out-of-the-box installation.  I have added the code as you describe above to cakephp.dataTables.js after the 
`/* create new instance */
    var table = $(id).dataTable(data);`

What else needs to be changed in order to get the column search working?
Thanks,
D
